In [15]:
import numpy as np
import pandas as pd

In [16]:
meta= pd.read_csv('/content/메타_전처리1.csv')
meta.head()

,작품명,장르,방송사,전체회차,출연자,시작일,종료일,요일,월,화,...,한예리,한지민,한지현,한지혜,한채영,한효주,함은정,현빈,황민현,황정음
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",2018-07-01 0:00,2018-09-16 0:00,수일,0,0,...,0,0,0,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']",2019-01-02 0:00,2019-02-07 0:00,수목,0,0,...,0,0,0,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",2019-01-02 0:00,2019-05-31 0:00,월화수목금,1,1,...,0,0,0,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",2019-01-07 0:00,2019-03-26 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",2019-01-07 0:00,2019-03-04 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0

In [17]:
meta.columns

Index(['작품명', '장르', '방송사', '전체회차', '출연자', '시작일', '종료일', '요일', '월', '화',
       ...
       '한예리', '한지민', '한지현', '한지혜', '한채영', '한효주', '함은정', '현빈', '황민현', '황정음'],
      dtype='object', length=1327)

In [18]:
meta = meta.drop(meta.columns[156:], axis=1)
meta

,작품명,장르,방송사,전체회차,출연자,시작일,종료일,요일,월,화,...,캠퍼스,케이퍼,코미디,코믹,코믹 미스터리 사극 드라마,클래식,타임 크로싱,판타지,판타지 드라마,판타지 로코 드라마
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",2018-07-01 0:00,2018-09-16 0:00,수일,0,0,...,0,0,0,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']",2019-01-02 0:00,2019-02-07 0:00,수목,0,0,...,0,0,0,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",2019-01-02 0:00,2019-05-31 0:00,월화수목금,1,1,...,0,0,0,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",2019-01-07 0:00,2019-03-26 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",2019-01-07 0:00,2019-03-04 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,12,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']",2023-06-23 0:00,2023-07-29 0:00,금토,0,0,...,0,0,0,0,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,12,"['김태리', ' 오정세', ' 홍경']",2023-06-23 0:00,2023-07-29 0:00,금토,0,0,...,0,0,0,0,0,0,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",16,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'...",2023-06-24 0:00,2023-08-13 0:00,토일,0,0,...,0,0,0,0,0,0,0,0,0,0
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,16,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']",2023-06-26 0:00,2023-08-15 0:00,월화,1,1,...,0,0,0,0,0,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,16,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']",2023-06-28 0:00,2023-08-17 0:00,수목,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
genre_groups = {
    '액션': ['액션', '스포츠', '사이언스 액션 히어로'],
    '코미디': ['코미디', '로맨틱코미디', '로코', '로맨틱 코미디', '로맨틱 코미디 드라마', '코믹', '블랙 코미디', '코믹 미스터리 사극 드라마'],
    '멜로': ['드라마', '멜로', '로맨스', '로맨스 드라마', '로맨스드라마', '로맨틱드라마', '멜로 로맨스 코미디', '멜로멜로', '멜로 로맨스', '프라이빗 오피스 멜로', '학원물 로맨스', '로맨틱', '청춘'],
    '스릴러': ['스릴러', '범죄', '법률', '범죄물', '법정', '블록버스터', '서스펜스', '서스펜스 추리', '피카레스크', '슬래셔 스릴러', '정치 스릴러', '타임 크로싱', '엑소시즘', '하드보일드'],
    '공포': ['공포', '호러', '금융'],
    '판타지': ['판타지', '판타지 드라마', '판타지 로코 드라마', '판타지 액션 로맨스', '휴먼 판타지 드라마', '판타지 사극 드라마'],
    '가족': ['가족', '어드벤처', '첩보', '뮤지컬', '시대극', '휴머니즘', '회사 드라마', '메디컬', '휴먼'],
    '미스터리': ['미스터리', '미스터리 멜로', '미스터리 스릴러', '미스터리 수사물', '정치', '경제', '비즈니스'],
    '전쟁': ['전쟁', '사극', '전쟁 스릴러'],
    'SF': ['SF']
}

In [20]:
# genre_groups 딕셔너리에 정의된 각 그룹에 속하는 열들을 찾아서 grouped_genres에 저장
grouped_genres = {}
for group, genres in genre_groups.items():
    grouped_genres[group] = [genre for genre in meta.columns if any(g in genre for g in genres)]

In [21]:
#grouped_genres 딕셔너리에 저장된 장르 그룹들과
#그에 해당하는 열들을 사용하여 새로운 데이터프레임 만들
grouped_df = pd.DataFrame()
for group, genres in grouped_genres.items():
    grouped_df[group] = meta[genres].sum(axis=1)

In [22]:
grouped_df

     액션  코미디  멜로  스릴러  공포  판타지  가족  미스터리  전쟁  SF
0     0    0   2    0   0    0   0     0   0   0
1     0    0   1    0   0    0   0     0   0   0
2     0    0   1    0   0    0   0     0   0   0
3     0    0   1    1   0    0   0     0   0   0
4     0    0   0    0   0    0   0     0   1   0
..   ..  ...  ..  ...  ..  ...  ..   ...  ..  ..
389   0    0   0    2   0    0   0     0   0   0
390   0    0   0    1   0    1   0     1   0   0
391   0    0   2    0   0    0   0     0   0   1
392   0    1   1    0   1    0   0     0   0   0
393   0    0   1    0   0    0   0     0   0   0

[394 rows x 10 columns]

In [23]:
#작품명과 기타 데이터 살리기
sliced_meta = meta.iloc[:, :5]
sliced_meta

,작품명,장르,방송사,전체회차,출연자
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']"
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']"
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']"
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']"
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']"
...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,12,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']"
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,12,"['김태리', ' 오정세', ' 홍경']"
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",16,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'..."
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,16,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']"
393,기적의 형제,['드라마'],JTBC,16,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']"

In [24]:
merged_df = pd.concat([sliced_meta, grouped_df], axis=1)
merged_df

,작품명,장르,방송사,전체회차,출연자,액션,코미디,멜로,스릴러,공포,판타지,가족,미스터리,전쟁,SF
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",24,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",0,0,2,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",12,"['박선호', ' 김소혜', ' 주우재 ']",0,0,1,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,3,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",0,0,1,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,40,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",0,0,1,1,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,16,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,12,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']",0,0,0,2,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,12,"['김태리', ' 오정세', ' 홍경']",0,0,0,1,0,1,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",16,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'...",0,0,2,0,0,0,0,0,0,1
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,16,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']",0,1,1,0,1,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,16,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']",0,0,1,0,0,0,0,0,0,0

In [25]:
#각 셀의 원핫인코딩을 살리기 위해 2이상인 것들은 1로 대체함
def replace(x):
    try:
        numeric = pd.to_numeric(x)
    except:
        numeric = float('nan')

    if pd.notnull(numeric) and numeric >= 2:
        return 1
    else:
        return x

In [26]:
merged_df = merged_df.applymap(replace)
merged_df

,작품명,장르,방송사,전체회차,출연자,액션,코미디,멜로,스릴러,공포,판타지,가족,미스터리,전쟁,SF
0,에이틴,"['웹드라마', ' 학원물', ' 로맨스']","V LIVE, 네이버TV, 유튜브, 페이스북",1,"['신예은', ' 이나은', ' 신승호', ' 김동희 ']",0,0,1,0,0,0,0,0,0,0
1,최고의 치킨,['드라마'],"iHQ DRAMA, MBN",1,"['박선호', ' 김소혜', ' 주우재 ']",0,0,1,0,0,0,0,0,0,0
2,왼손잡이 아내,"['복수', ' 멜로']",KBS 2TV,1,"['이수경', ' 김진우', ' 진태현', ' 하연주', ' 이승연 ']",0,0,1,0,0,0,0,0,0,0
3,동네변호사 조들호 2: 죄와 벌,['법률 드라마'],KBS 2TV,1,"['박신양', ' 고현정', ' 이민지', ' 변희봉 ']",0,0,1,1,0,0,0,0,0,0
4,왕이 된 남자,['사극'],tvN,1,"['여진구', ' 김상경', ' 이세영', ' 정혜영', ' 장광', ' 권해효 ']",0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,넘버스 : 빌딩숲의 감시자들,"['오피스', ' 복수', ' 범죄', ' 스릴러']",MBC,1,"['김명수', ' 최진혁', ' 최민수', ' 연우 ']",0,0,0,1,0,0,0,0,0,0
390,악귀,"['판타지', ' 미스터리', ' 스릴러']",SBS TV,1,"['김태리', ' 오정세', ' 홍경']",0,0,0,1,0,1,0,1,0,0
391,아씨두리안,"['SF', ' 드라마', ' 로맨스']","TV CHOSUN, 쿠팡플레이",1,"['박주미', ' 최명길', ' 김민준', ' 한다감', ' 전노민', ' 윤해영'...",0,0,1,0,0,0,0,0,0,1
392,가슴이 뛴다,"['공포', ' 로맨스', ' 코미디']",KBS 2TV,1,"['옥택연', ' 원지안', ' 박강현', ' 윤소희 ']",0,1,1,0,1,0,0,0,0,0
393,기적의 형제,['드라마'],JTBC,1,"['정우', ' 배현성', ' 박유림', ' 오만석', ' 이기우 ']",0,0,1,0,0,0,0,0,0,0

In [27]:
merged_df.to_csv("meta_장르병합.csv", index=False, encoding='cp949')